server:
  port: 8081
spring:
  # 邮件配置
  #  mail:
  #    # 邮件服务器地址
  #    host: smtp.qq.com
  #    # 协议
  #    protocol: smtp
  #    # 编码格式
  #    default-encoding: utf-8
  #    # 授权码（在邮箱开通服务时获取）
  #    password: avdcovyhrgbmbejh
  #    # 发送者邮箱地址
  #    username: 1060968795@qq.com
  #    # 端口（不同邮箱端口号不同）
  #    port: 465
  #    #使用了465 SSL 端口，但是不设置ssl，则导致该错误
  #    properties.mail.smtp.ssl.enable: true

  # rabbitmq配置
  #  rabbitmq:
  #    # 用户名
  #    username: guest
  #    # 密码
  #    password: guest
  #    # 服务器地址
  #    host: 192.168.6.142
  #    # 端口
  #    port: 5672
  #    listener:
  #      simple:
  #        #开启手动确认
  #        acknowledge-mode: manual
  #    # 消息确认回调
  #    publisher-confirm-type: correlated
  #    # 消息失败回调
  #    publisher-returns: true
  #  redis:
  #    #超时时间
  #    timeout: 10000
  #    #服务器地址
  #    host: localhost
  #    #服务器端口
  #    port: 6379
  #    #数据库
  #    database: 0
  #    #密码
  #    #    password: root
  #    lettuce:
  #      pool:
  #        #最大连接数，默认8
  #        max-active: 1024
  #        #最大连接阻塞等待时间，默认-1
  #        max-wait: 10000
  #        #最大空闲连接
  #        max-idle: 200
  #        #最小空闲连接
  #        min-idle: 5
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emp_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 946825
    hikari:
      # 连接名称
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间， 默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活， 默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认3000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 自动驼峰命名
    map-underscore-to-camel-case: false
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.zgm.server.pojo
# Mybatis SQL 打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.zgm.server.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: emp-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer